#!/usr/bin/env python3

import argparse
import shlex
import subprocess
from pathlib import Path

DIR: Path = Path("frontend")


def run(*cmd: str | Path) -> None:
    print(f"$ {shlex.join(str(arg) for arg in cmd)}")
    subprocess.run(cmd, check=True, cwd=DIR)


parser = argparse.ArgumentParser()
parser.add_argument(
    "--env",
    metavar="NAME",
    help="name of the build environment to use. A corresponding file"
    " '.env.NAME' must be present in the frontend/ directory",
)
args = parser.parse_args()

run(
    "yarnpkg",
    "install",
    # Yarnpkg complains about incompatible node versions, but the build seems to
    # run fine, so we just tell it to shut up.
    "--ignore-engines",
)

if args.env is None:
    run("yarnpkg", "build")
else:
    run("yarnpkg", "build", "--mode", args.env)
