#!/usr/bin/env python3

import argparse
import shutil
from pathlib import Path

DIR: Path = Path("frontend")


def rm(path: Path) -> None:
    print(f"Removing {path}")
    shutil.rmtree(path, ignore_errors=True)


parser = argparse.ArgumentParser()
parser.add_argument(
    "--all",
    "-a",
    action="store_true",
    help="remove node_modules as well",
)
args = parser.parse_args()

rm(DIR / "dist")

if args.all:
    rm(DIR / "node_modules")
