#!/usr/bin/env python3

import argparse
import shlex
import subprocess
from pathlib import Path

DIR: Path = Path("backend")


def run(*cmd: str | Path) -> None:
    print(f"$ {shlex.join(str(arg) for arg in cmd)}")
    subprocess.run(cmd, check=True, cwd=DIR)


parser = argparse.ArgumentParser()
_args = parser.parse_args()

run("mvn", "clean")
